In [10]:
import pandas as pd

In [11]:
pd.read_parquet("../artifacts/augmented/train_meta_aug.parquet")

,z,z_err,ebv,SpecType,English Translation,split,target,μ
object_id,,,,,,,,
Dornhoth_fervain_onodrim,3.034333,NaN,0.110,AGN,Trawn Folk (Dwarfs) + northern + Ents (people),split_01,0,47.105850
Dornhoth_galadh_ylf,0.418862,NaN,0.058,SN II,Trawn Folk (Dwarfs) + tree + drinking vessel,split_01,0,41.869428
Elrim_melethril_thul,0.462400,NaN,0.577,AGN,Elves + lover (fem.) + breath,split_01,0,42.124069
Ithil_tobas_rodwen,0.693065,NaN,0.012,AGN,moon + roof + noble maiden,split_01,0,43.183313
Mirion_adar_Druadan,0.419764,NaN,0.058,AGN,"jewel, Silmaril + father + Wild Man",split_01,0,41.874952
...,...,...,...,...,...,...,...,...
rach_lass_tathar_aug_0,0.250174,NaN,0.056,TDE,"wagon, wain + leaf + tathar",split_20,1,40.573266
rach_lass_tathar_aug_1,0.313944,NaN,0.056,TDE,"wagon, wain + leaf + tathar",split_20,1,41.137796
rach_lass_tathar_aug_2,0.292944,NaN,0.056,TDE,"wagon, wain + leaf + tathar",split_20,1,40.964575
rach_lass_tathar_aug_3,0.264488,NaN,0.056,TDE,"wagon, wain + leaf + tathar",split_20,1,40.710649
rach_lass_tathar_aug_4,0.269509,NaN,0.056,TDE,"wagon, wain + leaf + tathar",split_20,1,40.757228

In [12]:
pd.read_parquet("../artifacts/augmented/train_obs_aug.parquet")

,object_id,mjd,flux,flux_err,filter,flux_lupt
0,Dornhoth_fervain_onodrim,63314.466200,-1.711444,0.384016,z,1.673477
1,Dornhoth_fervain_onodrim,63780.967400,11.427573,0.276310,r,-4.042027
2,Dornhoth_fervain_onodrim,63789.769300,6.092316,1.619329,y,-1.508275
3,Dornhoth_fervain_onodrim,63794.170200,4.248717,0.410170,r,-2.548216
4,Dornhoth_fervain_onodrim,63794.170200,5.562850,0.550111,i,-2.522583
...,...,...,...,...,...,...
19877,rach_lass_tathar_aug_4,52155.653515,-1.213097,1.635173,i,0.394035
19878,rach_lass_tathar_aug_4,52155.653515,1.966470,2.462116,z,-0.422816
19879,rach_lass_tathar_aug_4,52159.999795,-0.584730,0.677274,r,0.455233
19880,rach_lass_tathar_aug_4,52162.172852,1.420410,2.219545,u,-0.341741
19881,rach_lass_tathar_aug_4,52162.172852,0.079176,0.720888,r,-0.059594

In [13]:
pd.read_parquet("../artifacts/features/train_feats.parquet")

,z,z_err,ebv,target,μ,Blue_Excess_Max,Blue_Excess_Mean,Blue_Excess_Min,Color_g_r_Early,Color_g_r_Late,...,u_Peak_Uncertainty,u_Rise_Time,y_Peak_Flux,y_Peak_Time,y_Peak_Uncertainty,y_Rise_Time,z_Peak_Flux,z_Peak_Time,z_Peak_Uncertainty,z_Rise_Time
object_id,,,,,,,,,,,,,,,,,,,,,
Dornhoth_fervain_onodrim,3.034333,NaN,0.110,0,47.105850,0.543753,-0.191712,-3.596268,0.102856,-0.130025,...,2.453765,460.752943,20.560697,460.752943,2.413109,460.752943,22.464834,460.752943,1.523667,460.752943
Dornhoth_galadh_ylf,0.418862,NaN,0.058,0,41.869428,0.656178,-0.174624,-1.945405,0.104060,-0.538813,...,1.012072,1446.217959,4.107929,1590.839755,0.692225,1590.839755,3.519293,1590.839755,0.487412,1590.839755
Elrim_melethril_thul,0.462400,NaN,0.577,0,42.124069,2.716374,0.666537,-1.453583,0.040588,1.293255,...,2.356366,369.190347,7.376880,713.768004,1.490578,713.768004,7.270946,713.768004,0.964840,713.768004
Ithil_tobas_rodwen,0.693065,NaN,0.012,0,43.183313,3.088926,0.261316,-4.569755,0.522052,0.286282,...,0.264662,1166.699143,1.661088,1108.364186,0.190170,1108.364186,1.807783,1108.364186,0.133317,1108.364186
Mirion_adar_Druadan,0.419764,NaN,0.058,0,41.874952,1.160848,0.228564,-1.667355,0.712955,0.386370,...,0.194930,764.065520,1.539603,719.120490,0.371037,719.120490,1.822040,719.120490,0.240332,719.120490
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
rach_lass_tathar_aug_0,0.250174,NaN,0.056,1,40.573266,0.242775,-0.133091,-0.812391,0.025960,0.159028,...,1.403486,1430.575243,7.104903,1430.575243,1.964794,1430.575243,8.061332,1430.575243,1.541488,1430.575243
rach_lass_tathar_aug_1,0.313944,NaN,0.056,1,41.137796,0.414735,-0.073459,-0.838347,0.036133,0.169407,...,0.719511,1503.547176,5.452966,1503.547176,1.086885,1503.547176,6.145079,1503.547176,0.790894,1503.547176
rach_lass_tathar_aug_2,0.292944,NaN,0.056,1,40.964575,0.343373,-0.133615,-1.924311,0.025660,0.153340,...,0.887015,1479.516612,5.972991,1479.516612,1.304461,1479.516612,6.743860,1479.516612,0.976331,1479.516612
rach_lass_tathar_aug_3,0.264488,NaN,0.056,1,40.710649,0.268939,-0.161953,-1.114921,0.022396,0.176553,...,1.173885,1446.953816,6.633652,1446.953816,1.688016,1446.953816,7.491374,1446.953816,1.295839,1446.953816
rach_lass_tathar_aug_4,0.269509,NaN,0.056,1,40.757228,0.278644,-0.167690,-1.256728,0.013111,0.179892,...,1.105297,1452.699687,6.479726,1452.699687,1.601905,1452.699687,7.307737,1452.699687,1.221571,1452.699687

In [14]:
pd.read_parquet("../artifacts/features/test_feats.parquet")

,z,z_err,ebv,μ,Blue_Excess_Max,Blue_Excess_Mean,Blue_Excess_Min,Color_g_r_Early,Color_g_r_Late,Color_g_r_Mid,...,u_Peak_Uncertainty,u_Rise_Time,y_Peak_Flux,y_Peak_Time,y_Peak_Uncertainty,y_Rise_Time,z_Peak_Flux,z_Peak_Time,z_Peak_Uncertainty,z_Rise_Time
object_id,,,,,,,,,,,,,,,,,,,,,
Eluwaith_Mithrim_nothrim,0.5393,0.03013,0.610,42.523697,2.604986,0.244138,-1.757482,-0.331556,0.218885,1.026531,...,3.231645,218.636224,10.366248,699.635918,2.092576,699.635918,12.429904,699.635918,1.327900,699.635918
Eru_heledir_archam,0.7282,0.03508,0.058,43.314324,1.309552,0.387917,-2.551719,0.530095,0.445834,0.383552,...,0.365945,1397.066914,2.722518,271.651900,0.348200,271.651900,2.704396,271.651900,0.221745,271.651900
Gonhir_anann_fuin,0.6026,0.03185,0.070,42.814410,0.397196,0.166557,-0.217741,0.062935,0.254962,0.160730,...,0.161504,1418.994973,1.234715,1418.994973,0.256060,1418.994973,1.479052,1418.994973,0.177382,1418.994973
Gwathuirim_haradrim_tegilbor,0.5298,0.03013,0.014,42.477324,1.200773,-0.164297,-2.049151,-0.062303,-0.574771,0.032078,...,0.213091,315.210171,2.010839,315.210171,0.299253,315.210171,2.764370,315.210171,0.173982,315.210171
achas_minai_maen,0.1654,0.02304,0.027,39.569740,2.328203,-0.019676,-1.778795,-0.528996,-0.200865,0.597911,...,1.490304,918.765698,14.037507,957.047602,1.358946,957.047602,12.971715,957.047602,0.997653,957.047602
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ungol_ulug_saew,0.7611,0.03585,0.030,43.431617,2.620764,0.560088,-2.472367,0.410648,0.373855,0.822536,...,0.445084,275.603308,2.546333,336.848488,0.534918,336.848488,2.842790,336.848488,0.320511,336.848488
uruk_Ennor_tirith,0.4788,0.02987,0.058,42.214240,1.213503,0.089960,-0.853834,-0.135538,0.085394,0.264515,...,0.264951,1847.451729,1.198677,1847.451729,0.332777,1847.451729,1.543943,1847.451729,0.224116,1847.451729
ylf_faen_lost,0.2840,0.02611,0.017,40.887305,1.077729,-0.189296,-3.723389,-0.069570,-0.073190,-0.193404,...,0.568427,1844.346533,4.385237,1844.346533,0.610192,1844.346533,5.765172,1844.346533,0.393882,1844.346533
yll_firiel_ruith,0.9608,0.03868,0.095,44.052815,0.849087,-0.056839,-2.995351,0.245947,0.403349,-0.187151,...,0.113278,1528.170514,1.135531,1528.170514,0.210066,1528.170514,1.319982,1528.170514,0.132371,1528.170514
yll_randir_bragol,0.3571,0.02705,0.014,41.462600,0.914452,0.314260,-1.304352,0.273003,0.508137,0.418589,...,0.430750,1262.036702,2.779097,1183.159408,0.538890,1183.159408,3.092837,1183.159408,0.399915,1183.159408

In [15]:
import optuna
from optuna.visualization import plot_optimization_history, plot_param_importances

# Connect to the EXISTING database and study
# (Do not create a new study, just load it)
study = optuna.load_study(
    study_name="study-lgb-v5", 
    storage="sqlite:///D:/root/dev/py/mallorn/optuna.db"
)

# These will auto-update every time you re-run the cell
print(f"Current Trials: {len(study.trials)}")
plot_optimization_history(study)

Current Trials: 640

In [16]:
plot_param_importances(study)

In [17]:
import pandas as pd
from catboost import CatBoostClassifier, Pool
from mallorn.common import SEED

# 2. Prepare your data (Make sure X_train/y_train are loaded in your notebook)
feats_df = pd.read_parquet("../artifacts/features/train_feats.parquet")
X_train = feats_df.drop(columns=["target"])
y_train = feats_df["target"]

n_pos = y_train.sum()
n_neg = len(y_train) - n_pos
scale_pos = n_neg / n_pos if n_pos > 0 else 1.0

# 1. Load the Best Parameters from your fixed study
best_params = study.best_params
best_params.update({
    # "task_type": "GPU",
    "loss_function": "Logloss",
    "scale_pos_weight": scale_pos,
    "eval_metric": "AUC",
    "verbose": False,
    "random_seed": SEED,
    "allow_writing_files": False,
})
print(f"Retraining model with best params: {best_params}")

# 3. Retrain the model
# Note: You might need to manually add fixed params that weren't tuned 
# (e.g., iterations, loss_function) if they aren't in best_params.
model = CatBoostClassifier(
    **best_params,
)
model.fit(X_train, y_train)

# 4. Get Feature Importance
importance = model.get_feature_importance(type='FeatureImportance', prettified=True)

# 5. Plotting (Simple Bar Chart)
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.barplot(x="Importances", y="Feature Id", data=importance.head(20)) # Top 20 features
plt.title('CatBoost Feature Importance')
plt.show()

Retraining model with best params: {'num_leaves': 56, 'max_depth': 6, 'learning_rate': 0.014246973662148067, 'min_child_samples': 37, 'subsample': 0.7595291411370892, 'colsample_bytree': 0.8493154697499203, 'reg_alpha': 0.17045506518230655, 'reg_lambda': 0.017821927003781254, 'loss_function': 'Logloss', 'scale_pos_weight': np.float64(3.260135135135135), 'eval_metric': 'AUC', 'verbose': False, 'random_seed': 67, 'allow_writing_files': False}

TypeError: CatBoostClassifier.__init__() got an unexpected keyword argument 'colsample_bytree'